matrix:
  include:
  - language: python
    name: 'pytest'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install pytest
    - pip install pytest-cov
    - cp config.example.yml config.yml
    script:
    - pytest
  - language: python
    name: 'flake8'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install flake8
    script:
    - flake8 monograph
  - language: python
    name: 'mypy'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install mypy
    script:
    - mypy monograph
  - language: node_js
    name: 'npm run test'
    node_js:
    - '12.16.3'
    before_install:
    - cd webapp
    install:
    - npm install
    - npm install codecov -g
    script:
    - npm run build
    - npm run test
    after_success:
    - codecov
  - language: node_js
    name: 'npm run lint'
    node_js:
    - '12.16.3'
    before_install:
    - cd webapp
    install:
    - npm install
    script:
    - npm run lint
